Repository DO-SOPT-CDS-TEAM-WEB7/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [#1] feat: 기초세팅
  skyscanner/.gitignore
  skyscanner/build.gradle
  skyscanner/gradle/wrapper/gradle-wrapper.jar
  skyscanner/gradle/wrapper/gradle-wrapper.properties
  skyscanner/gradlew
  skyscanner/gradlew.bat
  skyscanner/settings.gradle
  skyscanner/src/main/java/org/third/thirdseminar/ThirdseminarApplication.java
  skyscanner/src/main/java/org/third/thirdseminar/common/ApiResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/common/advice/ControllerExceptionAdvice.java
  skyscanner/src/main/java/org/third/thirdseminar/common/config/JpaAuditingConfig.java
  skyscanner/src/main/java/org/third/thirdseminar/common/config/SecurityConfig.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Error.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Success.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/model/CustomException.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/model/NotFoundException.java
  skyscanner/src/main/resources/data.sql
  skyscanner/src/test/java/org/third/thirdseminar/SecondseminarApplicationTests.java
Labels: Feat

#7 [#4] feat: 항공권 조회 페이지 구현하기
  skyscanner/.gitignore
  skyscanner/build.gradle
  skyscanner/gradle/wrapper/gradle-wrapper.jar
  skyscanner/gradle/wrapper/gradle-wrapper.properties
  skyscanner/gradlew
  skyscanner/gradlew.bat
  skyscanner/settings.gradle
  skyscanner/src/main/java/org/third/thirdseminar/ThirdseminarApplication.java
  skyscanner/src/main/java/org/third/thirdseminar/common/ApiResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/common/advice/ControllerExceptionAdvice.java
  skyscanner/src/main/java/org/third/thirdseminar/common/config/JpaAuditingConfig.java
  skyscanner/src/main/java/org/third/thirdseminar/common/config/SecurityConfig.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/AirReservationController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/reqeust/AirReservationReqeust.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirReservationResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/DateDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TimeRangeDto.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Air.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Reservation.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Ticket.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/TimeRange.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Error.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Success.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/model/CustomException.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/model/NotFoundException.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/ReservationJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/TickectJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/service/ReservationService.java
  skyscanner/src/test/java/org/third/thirdseminar/SecondseminarApplicationTests.java
Labels: Feat

#5 [#3] feat : 메인페이지 뷰 구현하기
  README.md
  skyscanner/.gitignore
  skyscanner/build.gradle
  skyscanner/gradle/wrapper/gradle-wrapper.properties
  skyscanner/settings.gradle
  skyscanner/src/main/java/org/third/thirdseminar/ThirdseminarApplication.java
  skyscanner/src/main/java/org/third/thirdseminar/common/advice/ControllerExceptionAdvice.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/AirReservationController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/MainController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/TicketController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/AirReservationRequest.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/TicketRequestDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirReservationResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirResultDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/CardDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/CardListDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/DateDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TicketDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TicketPageDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TimeRangeDto.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Air.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Reservation.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Ticket.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/TimeRange.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Error.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Success.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/AirJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/ReservationJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/TicketJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/service/MainService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/ReservationService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/TicketService.java
  skyscanner/src/main/resources/data.sql
Labels: Feat

#13 [Refactor] 명세서랑 다른 점 수정 및 로직 변경
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/TicketRequestDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirResultDto.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Error.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/ReservationJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/service/MainService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/ReservationService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/TicketService.java
Labels: Refactor

#16 [Merge] merge to main
  skyscanner/build.gradle
  skyscanner/gradle/wrapper/gradle-wrapper.properties
  skyscanner/src/main/java/org/third/thirdseminar/ThirdseminarApplication.java
  skyscanner/src/main/java/org/third/thirdseminar/common/ApiResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/common/advice/ControllerExceptionAdvice.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/AirReservationController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/MainController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/TicketController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/AirReservationController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/reqeust/AirReservationReqeust.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/AirReservationRequest.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/CreateReservationRequest.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/request/TicketRequestDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirMinPriceDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirMinPriceResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirReservationResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/AirResultDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/CardDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/CardListDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/CreateReservationResponse.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/DateDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/ReservationDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TicketDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TicketPageDto.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/dto/response/TimeRangeDto.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Air.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/BaseTimeEntity.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Reservation.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/ReservationMinPriceDTO.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/ReservationResult.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/Ticket.java
  skyscanner/src/main/java/org/third/thirdseminar/domain/TimeRange.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Error.java
  skyscanner/src/main/java/org/third/thirdseminar/exception/Success.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/AirJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/ReservationJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/ReservationResultJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/TickectJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/infrastructure/TicketJpaRepository.java
  skyscanner/src/main/java/org/third/thirdseminar/service/MainService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/ReservationService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/TicketService.java
Labels: merge

#19 [Merge] merge to main
  skyscanner/src/main/java/org/third/thirdseminar/controller/AirReservationController.java
  skyscanner/src/main/java/org/third/thirdseminar/controller/TicketController.java
  skyscanner/src/main/java/org/third/thirdseminar/service/ReservationService.java
  skyscanner/src/main/java/org/third/thirdseminar/service/TicketService.java
Labels: bug
